
spring:
  datasource:
    url: jdbc:h2:file:./bd/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
server:
  port: 2222
